[package]
name = "grilme99/roact-rodux"
version = "0.5.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "core-packages/roact-compat@17.0.1-rc.16.1"
Rodux = "roblox/rodux@4.0.0-rc.0"
